// esbuild.config.mjs — bundle packages/host → dist/extension.js
import { build } from "esbuild";

await build({
  entryPoints: ["packages/host/src/extension.ts"],
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  outfile: "dist/extension.js",
  // Native .node addons + the embedder must stay real dependencies so pi's
  // `npm install` prebuilds them per-OS. Never inline these.
  external: ["better-sqlite3", "sqlite-vec", "onnxruntime-node", "onnxruntime-web", "fastembed", "@xenova/transformers", "@earendil-works/pi-ai"],
  // Internal @spider/* packages ARE bundled (they compile into the ship artifact).
  banner: { js: "// spider extension bundle — generated by esbuild. Do not edit." },
  logLevel: "info",
});
console.log("esbuild: wrote dist/extension.js");
