// esbuild.config.mjs — bundle packages/host → dist/extension.js
import { build } from "esbuild";

await build({
  entryPoints: ["packages/host/src/extension.ts"],
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  outfile: "dist/extension.js",
  // Two classes stay EXTERNAL (never inlined):
  //  1. Native .node addons + the embedder — pi's `npm install` prebuilds them per-OS.
  //  2. pi's host-provided peer packages — per pi docs/packages.md, pi bundles these
  //     for extensions at runtime; bundling our own copy bloats the artifact (~6.5mb)
  //     and risks duplicate-module state. List: pi-ai, pi-agent-core, pi-coding-agent,
  //     pi-tui, typebox (+ their subpaths).
  external: [
    // native / embedder
    "better-sqlite3", "sqlite-vec", "onnxruntime-node", "onnxruntime-web", "fastembed", "@xenova/transformers",
    // pi host-provided peers (do NOT bundle)
    "@earendil-works/pi-ai", "@earendil-works/pi-ai/*",
    "@earendil-works/pi-agent-core", "@earendil-works/pi-agent-core/*",
    "@earendil-works/pi-coding-agent", "@earendil-works/pi-coding-agent/*",
    "@earendil-works/pi-tui", "@earendil-works/pi-tui/*",
    "typebox", "typebox/*",
  ],
  // Internal @spider/* packages ARE bundled (they compile into the ship artifact).
  banner: { js: "// spider extension bundle — generated by esbuild. Do not edit." },
  logLevel: "info",
});
console.log("esbuild: wrote dist/extension.js");
