// vite.config.mjs — bundle packages/host/src/extension.ts → dist/extension.js
// Vite 8 (Rolldown + Oxc) SSR/node build, straight from TS source (no tsc pre-step).
// SSR (not `lib`) so deps resolve via NODE export conditions (e.g. turndown's node
// build, not its browser build) and there are no browser polyfills.
import { defineConfig } from "vite";
import { builtinModules } from "node:module";

// Two classes stay EXTERNAL (never inlined):
//  1. Native .node addons + the embedder — pi's `npm install` prebuilds them per-OS.
//  2. pi's host-provided peer packages — per pi docs/packages.md pi provides these at
//     runtime; bundling our own copy bloats the artifact and risks duplicate modules.
const EXTERNAL = [
  "better-sqlite3", "sqlite-vec", "onnxruntime-node", "onnxruntime-web", "fastembed", "@huggingface/transformers", "@xenova/transformers", "turndown",
  "@earendil-works/pi-ai", "@earendil-works/pi-agent-core", "@earendil-works/pi-coding-agent", "@earendil-works/pi-tui", "typebox",
];
const builtins = new Set([...builtinModules, ...builtinModules.map((m) => `node:${m}`)]);
const isExternal = (id) =>
  builtins.has(id) || id.startsWith("node:") ||
  EXTERNAL.some((e) => id === e || id.startsWith(`${e}/`));

export default defineConfig({
  // SSR build: bundle every dep EXCEPT our explicit externals, using node conditions.
  ssr: {
    target: "node",
    noExternal: true,
  },
  build: {
    target: "node22",
    outDir: "dist",
    emptyOutDir: true,
    minify: false,
    sourcemap: false,
    ssr: "packages/host/src/extension.ts",
    rollupOptions: {
      external: isExternal,
      output: {
        format: "es",
        entryFileNames: "extension.js",
        banner: "// spider extension bundle — generated by vite (rolldown + oxc). Do not edit.",
        exports: "named",
      },
    },
    // single-file bundle (non-deprecated replacement for output.inlineDynamicImports)
    codeSplitting: false,
  },
});
