// jiti rewrites ordinary dynamic import() and can discard its query string.
// Execute the import in Node's main context with its native ESM loader instead.
// A plain Function constructor inside jiti's VM has no dynamic-import callback.
export function extensionShim(bundle, dev = false) {
  return `// spider ${dev ? "DEV" : "STABLE"} shim, generated by npm run ${dev ? "dev:link" : "link"}.
// Rebuilt files load fresh on /reload; unchanged files reuse their module instance.
import { statSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { constants, runInThisContext } from "node:vm";
import { isNativeError } from "node:util/types";
function withLoaderWarningSuppressed<T>(fn: () => T): T {
  const original = process.emitWarning;
  process.emitWarning = function(this: unknown, ...args: unknown[]) {
    const [warning, options] = args;
    const type = isNativeError(warning) ? warning.name
      : typeof options === "string" ? options
      : options && typeof options === "object" ? (options as { type?: string }).type : undefined;
    const message = isNativeError(warning) ? warning.message : warning;
    if (type === "ExperimentalWarning" && typeof message === "string"
      && /USE_MAIN_CONTEXT_DEFAULT_LOADER|vm.*dynamic.*import.*loader/i.test(message)) return;
    return Reflect.apply(original, this, args);
  } as typeof process.emitWarning;
  try {
    return fn();
  } finally {
    process.emitWarning = original;
  }
}
let nativeImport: ((u: string) => Promise<{ default: (pi: unknown) => unknown }>) | undefined;
let nativeSetupError: unknown;
const loaderErrorCodes = new Set([
  "ERR_MODULE_NOT_FOUND", "ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING",
  "ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING_FLAG", "ERR_UNSUPPORTED_ESM_URL_SCHEME",
  "ERR_UNKNOWN_FILE_EXTENSION", "ERR_PACKAGE_PATH_NOT_EXPORTED",
  "ERR_PACKAGE_IMPORT_NOT_DEFINED", "ERR_UNSUPPORTED_DIR_IMPORT",
]);
async function fallbackImport(bundle: string, original?: unknown) {
  try {
    return await import(bundle);
  } catch (fallbackError) {
    if (original !== undefined) {
      const message = (error: unknown) => error !== null && typeof error === "object" && "message" in error
        ? String(error.message) : String(error);
      throw new AggregateError([original, fallbackError],
        message(original) + " (fallback import also failed: " + message(fallbackError) + ")");
    }
    throw fallbackError;
  }
}
if (constants?.USE_MAIN_CONTEXT_DEFAULT_LOADER !== undefined) {
  try {
    nativeImport = withLoaderWarningSuppressed(() => runInThisContext("(u) => import(u)", {
      importModuleDynamically: constants.USE_MAIN_CONTEXT_DEFAULT_LOADER,
    }));
  } catch (error) {
    // Unsupported VM loader: plain import still loads spider, but needs restart after rebuilds.
    nativeSetupError = error;
  }
}
export default async function spider(pi: unknown): Promise<unknown> {
  const bundle = ${JSON.stringify(bundle)};
  let mod;
  if (nativeImport) {
    const stat = statSync(bundle, { bigint: true });
    const url = pathToFileURL(bundle);
    url.searchParams.set("build", stat.mtimeNs.toString() + "-" + stat.size.toString());
    try {
      // Node emits the experimental warning synchronously on the first import call.
      // Restore before awaiting so unrelated asynchronous work is never filtered.
      mod = await withLoaderWarningSuppressed(() => nativeImport!(url.href));
    } catch (error) {
      const code = (error as { code?: unknown } | null)?.code;
      if (typeof code !== "string" || !loaderErrorCodes.has(code)) throw error;
      mod = await fallbackImport(bundle, error);
    }
  } else {
    mod = await fallbackImport(bundle, nativeSetupError);
  }
  return mod.default(pi);
}
`;
}
