// scripts/link.mjs — install/remove the STABLE pi extension shim for a fixed
// (non-dev) install (`npm run link` / `npm run unlink`).
//
// Unlike dev-link.mjs (cache-busting hot-reload shim → spider-dev.ts, for the
// `npm run dev` watch loop), this writes a plain cached-import shim → spider.ts,
// pointing at THIS repo's built dist. Use it for a canonical install such as
// pi-init's ~/.local/share/spider. Removes any dev shim to avoid a double load.
import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const bundle = join(repoRoot, "dist", "extension.js");
const extDir = join(homedir(), ".pi", "agent", "extensions");
const shim = join(extDir, "spider.ts");
const devShim = join(extDir, "spider-dev.ts");

if (process.argv.includes("--unlink")) {
  if (existsSync(shim)) { rmSync(shim); console.log(`unlink — removed ${shim}`); }
  else console.log(`unlink — nothing to remove (${shim} absent)`);
} else {
  mkdirSync(extDir, { recursive: true });
  // A dev shim + a stable shim would double-load spider; drop the dev one.
  if (existsSync(devShim)) { rmSync(devShim); console.log(`link — removed stale dev shim ${devShim}`); }
  writeFileSync(shim,
`// spider — STABLE install shim, generated by \`npm run link\` (remove with \`npm run unlink\`).
// pi auto-discovers *.ts here (global, no project trust). Plain cached import of the built
// bundle — no cache-busting; this is a fixed install, not a dev hot-reload.
// To develop against a working tree instead, run \`npm run dev:link\` there.
import { pathToFileURL } from "node:url";
export default async function spider(pi: unknown): Promise<unknown> {
  const mod = await import(pathToFileURL(${JSON.stringify(bundle)}).href) as { default: (pi: unknown) => unknown };
  return mod.default(pi);
}
`);
  console.log(`link — wrote ${shim}\n  → ${bundle}\nNext: \`/reload\` in an interactive pi, or relaunch.`);
}
