import type { Pace } from "../dashboard-v4-contract.js";
import { element } from "./dom.js";
import { renderTable } from "./tables.js";
const NS = "http://www.w3.org/2000/svg";
const cleanups = new WeakMap<HTMLElement, () => void>();
let sequence = 0;
const number = (n: number | null) => n === null ? "unavailable" : new Intl.NumberFormat("en-US", { notation: n >= 1000 ? "compact" : "standard", maximumFractionDigits: 1 }).format(n).replace("K", "k");
const exact = (n: number | null) => n === null ? "unavailable" : new Intl.NumberFormat("en-US", { maximumFractionDigits: n < 10 ? 1 : 0 }).format(n);
const months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
export function disposePace(root: HTMLElement): void { cleanups.get(root)?.(); cleanups.delete(root); }
export function renderPace(document: Document, pace: Pace, _now: number): HTMLElement {
  const root = element(document, "div", undefined, "month-pace");
  root.setAttribute("data-danger", String(pace.overPace || pace.overBudget || (pace.scale !== null && (pace.projected ?? 0) > pace.scale)));
  const id = `pace-details-${++sequence}`, patternId = `pace-hatch-${sequence}`;
  const start = new Date(pace.period.start), last = new Date(pace.period.end - 1);
  const month = start.getUTCDate() === 1 ? months[start.getUTCMonth()]! : `to ${last.getUTCDate()} ${months[last.getUTCMonth()]}`;
  const extent = pace.scale !== null && pace.scale > 0 ? pace.scale : null;
  const used = extent === null ? 0 : Math.min(1, Math.max(0, (pace.used ?? 0) / extent));
  const ringPosition = (width: number) => extent === null ? 18 : Math.max(11, Math.min(width - 11, used * width));
  const projected = extent === null ? used : Math.max(used, Math.min(1, (pace.projected ?? 0) / extent));
  const amount = pace.used !== null && extent !== null && pace.used > extent ? `${number(pace.used)} · ${number(pace.used - extent)} over` : number(pace.used);
  const trigger = element(document, "button", undefined, "pace-trigger"); trigger.type = "button";
  trigger.setAttribute("aria-label", `${month} credit pace. ${number(pace.used)} credits used. Projected month end ${number(pace.projected)} credits. Details`);
  trigger.setAttribute("aria-expanded", "false"); trigger.setAttribute("aria-controls", id);
  const node = <K extends keyof SVGElementTagNameMap>(tag: K, attrs: Record<string, string | number> = {}, text?: string): SVGElementTagNameMap[K] => {
    const n = document.createElementNS(NS, tag); for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v)); if (text !== undefined) n.textContent = text; return n;
  };
  const svg = node("svg", { viewBox: "0 0 1000 40", preserveAspectRatio: "none", class: "pace-track", "aria-hidden": "true" });
  const defs = node("defs"), hatch = node("pattern", { id: patternId, width: 10, height: 10, patternUnits: "userSpaceOnUse", patternTransform: "rotate(30)" });
  hatch.append(node("path", { d: "M0 0v10", class: "pace-hatch-ink", "stroke-width": 3 })); defs.append(hatch);
  const fill = node("rect", { x: 0, y: 0, width: used * 1000, height: 40, class: "pace-fill" });
  const projection = node("rect", { x: used * 1000, y: 0, width: (projected - used) * 1000, height: 40, fill: `url(#${patternId})`, class: "pace-projection" });
  const label = node("text", { x: 18, y: 25, class: "pace-used" }, amount);
  const ring = node("circle", { cx: ringPosition(1000), cy: 20, r: 9, class: "pace-here", "vector-effect": "non-scaling-stroke" });
  const monthLabel = node("text", { x: 982, y: 24, "text-anchor": "end", class: "pace-month-label" }, month);
  if (extent !== null) svg.append(defs, projection, fill, label, ring, monthLabel);
  else svg.append(fill, label, monthLabel);
  trigger.append(svg);
  const overlay = node("svg", { class: "pace-overlay", viewBox: "0 0 1000 480", "aria-hidden": "false" });
  const pointer = node("path", { class: "pace-pointer", d: `M${ringPosition(1000) - 6} 8l6 -6 6 6` });
  const foreign = node("foreignObject", { x: Math.max(0, Math.min(630, ringPosition(1000) - 185)), y: 8, width: 370, height: 470 });
  const popover = element(document, "div", undefined, "pace-popover"); popover.id = id; popover.hidden = true;
  popover.setAttribute("role", "region"); popover.setAttribute("aria-label", "Credit pace details");
  popover.append(element(document, "h3", `${months[start.getUTCMonth()]} ${start.getUTCFullYear()}`));
  const rows: string[][] = [["Used", exact(pace.used)]];
  if (extent !== null) {
    if (pace.budget !== null) rows.push(["Budget", exact(pace.budget)], ["Even pace", exact(pace.evenPace)]);
    rows.push(["Projected month end", exact(pace.projected)]);
    if (pace.allowance !== null) rows.push(["Allowance", exact(pace.allowance)]);
    rows.push(["Remaining", exact(pace.remaining)]);
  } else rows.push(["Projected month end", exact(pace.projected)]);
  rows.push(["Days left", exact(pace.daysLeft)]);
  popover.append(renderTable(document, { caption: "Billing month pace in credits", columns: ["Measure", "Credits / days"], rows }));
  if (pace.overAtPace !== null) popover.append(element(document, "p", `${exact(pace.overAtPace)} over at this pace`, "pace-danger-note"));
  popover.append(element(document, "p", pace.usedSource === "counter" ? "Account-wide use, including use outside pi." : pace.counterAvailable ? "Used comes from pi's credits." : "Counter unavailable. Used comes from pi's credits.", "pace-detail-note"));
  if (pace.rateSource === "pi") popover.append(element(document, "p", "Projection uses pi's daily credits.", "pace-detail-note"));
  if (pace.budget === null) popover.append(element(document, "p", "/spider config set usage.monthlyBudget <credits> --global", "pace-budget-hint"));
  foreign.append(popover); overlay.append(pointer, foreign); root.append(trigger, overlay);
  overlay.setAttribute("visibility", "hidden");
  let disposed = false;
  // SVG attributes position the HTML table without style attributes, under style-src-attr 'none'.
  const position = () => {
    const view = document.defaultView; if (!view || disposed) return;
    const width = root.getBoundingClientRect().width; if (!width) return;
    const end = width * used, anchor = ringPosition(width), popWidth = Math.min(370, width), left = Math.max(0, Math.min(width - popWidth, anchor - popWidth / 2));
    overlay.setAttribute("viewBox", `0 0 ${width} 480`); foreign.setAttribute("x", String(left)); foreign.setAttribute("width", String(popWidth));
    pointer.setAttribute("d", `M${anchor - 6} 8l6 -6 6 6`);
    svg.setAttribute("viewBox", `0 0 ${width} 40`); fill.setAttribute("width", String(end)); projection.setAttribute("x", String(end)); projection.setAttribute("width", String((projected - used) * width)); ring.setAttribute("cx", String(anchor)); monthLabel.setAttribute("x", String(width - 18));
    const labelWidth = label.getComputedTextLength(); const after = extent === null || end < labelWidth + 52;
    label.setAttribute("data-after", String(after)); label.setAttribute("x", String(after ? end + 18 : 18));
    monthLabel.setAttribute("visibility", projected > .86 || used > .86 ? "hidden" : "visible");
  };
  const show = () => { if (disposed) return; popover.hidden = false; overlay.setAttribute("visibility", "visible"); root.setAttribute("data-open", "true"); trigger.setAttribute("aria-expanded", "true"); position(); };
  const hide = () => { popover.hidden = true; overlay.setAttribute("visibility", "hidden"); root.setAttribute("data-open", "false"); trigger.setAttribute("aria-expanded", "false"); };
  trigger.addEventListener("pointerenter", show); trigger.addEventListener("focus", show); trigger.addEventListener("click", show);
  root.addEventListener("pointerleave", () => { if (!root.contains(document.activeElement)) hide(); });
  root.addEventListener("focusout", event => { if (!root.contains(event.relatedTarget as Node | null)) hide(); });
  const escape = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); hide(); } };
  trigger.addEventListener("keydown", escape);
  const clickAway = (event: Event) => { if (!root.contains(event.target as Node)) hide(); };
  document.addEventListener("click", clickAway); document.defaultView?.addEventListener("resize", position);
  const observer = document.defaultView && typeof ResizeObserver !== "undefined" ? new ResizeObserver(position) : undefined; observer?.observe(root);
  void document.fonts?.ready?.then(position);
  cleanups.set(root, () => { disposed = true; observer?.disconnect(); document.removeEventListener("click", clickAway); document.defaultView?.removeEventListener("resize", position); });
  return root;
}
